# .streamlit/secrets.toml

[general]
# Credentials will be securely stored in environment variables
credentials = '''
  usernames:
    :
      email: 
      name: Gareth Higgins
      password: ${GARETH_HIGGINS_PASSWORD}

   :
      email: 
      name: Kyle Lillie
      password: ${KYLE_LILLIE_PASSWORD}

   
      email: 
      name: Shafiullah Qureshi
      password: ${SHAFIULLAH_QURESHI_PASSWORD}
'''

cookie_name = "${COOKIE_NAME}"  # Cookie name stored in the environment
cookie_key = "${COOKIE_KEY}"    # Cookie key stored in the environment
cookie_expiry_days = "${COOKIE_EXPIRY_DAYS}"

# API keys
OPENAI_API_KEY = "${OPENAI_API_KEY}"
SERPAPI_API_KEY = "${SERPAPI_API_KEY}"
