# .streamlit/secrets.toml

[general]
# Credentials will be securely stored in environment variables
credentials = '''
  usernames:
    gareth.higgins@gov.ab.ca:
      email: gareth.higgins@gov.ab.ca
      name: Gareth Higgins
      password: ${GARETH_HIGGINS_PASSWORD}

    kyle.lillie@gov.ab.ca:
      email: kyle.lillie@gov.ab.ca
      name: Kyle Lillie
      password: ${KYLE_LILLIE_PASSWORD}

    shafiullah.qureshi@gov.ab.ca:
      email: shafiullah.qureshi@gov.ab.ca
      name: Shafiullah Qureshi
      password: ${SHAFIULLAH_QURESHI_PASSWORD}
'''

cookie_name = "${COOKIE_NAME}"  # Cookie name stored in the environment
cookie_key = "${COOKIE_KEY}"    # Cookie key stored in the environment
cookie_expiry_days = "${COOKIE_EXPIRY_DAYS}"

# API keys
OPENAI_API_KEY = "${OPENAI_API_KEY}"
SERPAPI_API_KEY = "${SERPAPI_API_KEY}"
